### ISSUE TITLE
Appication test on every OS.

### ISSUE THREAD

**Issue by rocktimsaikia** [RocktimSaikia/github-feed-cli#2]
Currently, I was only able to test this tool in my Linux machine and a windows PC. It would be nice to know if it works on all the OSS.

- [x] Linux 
- [x] Windows
- [x] Mac

**Comment by lokiiarora** [comment]
I can help you on this, I happen to have a mac. @RocktimSaikia

**Comment by lokiiarora** [comment]
We could also add a CI / CD github action to automate this on every push.

**Comment by rocktimsaikia** [comment]
> We could also add a CI / CD github action to automate this on every push.

Yes. But not a fan of Github actions, but can be done in Travis :+1: . But I don't think tests that depends on systems `.gitconfig` file can be ran on these CI/CD platforms. But I am not sure ! Thats why I commented out this test case just in case Travis would not be able to run it
https://github.com/RocktimSaikia/github-feed-cli/blob/0e215566abd99da38fbb2f5b361f509ff3285a44/test.js#L17

**Comment by rocktimsaikia** [comment]
fixed in the recent commit.
